# Qwen2.5-VL 3B
artifact_path: hhm2000-heriot-watt-university/AgriPath-VLM/model-Qwen2_5_3B_ZS_VisFreeze:v3
model_name: AgriPath-Qwen2.5-VL-3B
run_name: Qwen-3B-FV-Eval
trc: False
job_type: NE_fv_eval
zs_type: frozen_vision